### ISSUE TITLE
Plural occurs for 1 minute

### ISSUE THREAD

**Issue by NielsdeBlaauw** [jimmiw/php-time-ago#13]
Looks the same as the issue fixed in 0.4.3 "Added a fix for “about 1 hour ago”, which would yield “1 hours ago” if the time was 1hour 30minutes. Giving a pluralization error."

The same occurs for minutes, where it renders the text '1 minutes ago'.

**Comment by NielsdeBlaauw** [comment]
It happens because of the `floor()` on [line 74](https://github.com/jimmiw/php-time-ago/blob/master/timeago.inc.php#L74)

**Comment by jimmiw** [comment]
This is fixed in version 0.4.7
