### ISSUE TITLE
How can I add my own translation files?

### ISSUE THREAD

**Issue by emados** [jimmiw/php-time-ago#32]
I want to add `it.php` translation file, I know I can do this by simply adding the file in the translations directory, but that does not seem like an ideal solution to me.

Is it possible to have a function that loads language from an array? (This way I can store translations in my production code and not the vendor directory)

**Comment by MartinTerp** [comment]
yes im missing this feature aswell.
Editing in vendor files will just overwrite on updates.

**Comment by misaon** [comment]
So create language file "it.php" and send pull request to this repository :+1:

**Comment by jimmiw** [comment]
This is now possible using the pull request #33
