### ISSUE TITLE
how to use timestamp ?

### ISSUE THREAD

**Issue by zieru** [jimmiw/php-time-ago#37]
not working using timestamp

**Comment by jimmiw** [comment]
see patch #29 
It has not been merged in yet though

**Comment by jimmiw** [comment]
Without thinking too much about it, you could get DateTime to convert the timestamp for you:

Just do what they did here:
http://php.net/manual/en/datetime.settimestamp.php#refsect1-datetime.settimestamp-examples

It should work like the following
```
$datetime = new DateTime();
$datetime->setTimestamp(1171502725);
$dateString = $datetime->format('Y-m-d H:i:s');

$timeAgo = new Westsworld\TimeAgo();
echo $timeAgo->inWords($dateString);
```
