### ISSUE TITLE
Add support for other languages i18n

### ISSUE THREAD

**Issue by gustavomanolo** [jimmiw/php-time-ago#4]
It would be great to add support for other languages. (i18n)
$timeAgo = new TimeAgo('es');

**Comment by 1baga** [comment]
how do i change the timezone to GMT+1

**Comment by jimmiw** [comment]
Very unrelated to this issue, but use the php function date_default_timezone_set ?

**Comment by cmfcmf** [comment]
> Does anyone have an idea as to what method for translations storage should be used?
Gettext seems a bit "over the top" if people want to add a new language, without having to do too much...

You could do it like so: 
- https://github.com/simshaun/recurr
- https://github.com/simshaun/recurr/blob/master/src/Recurr/Transformer/Translator.php
- https://github.com/simshaun/recurr/tree/master/translations

**Comment by jimmiw** [comment]
This is included in version 0.4.0 of this project.
