### ISSUE TITLE
[Insight] PHP methods should not contain too much logic

### ISSUE THREAD

**Issue by jimmiw** [jimmiw/php-time-ago#48]
> 6% of all methods have more than 50 lines. This violation is raised when more than 5% methods are too long.

- 60 lines for TimeAgo::inWords() in [**src/Westsworld/TimeAgo.php**](https://github.com/jimmiw/php-time-ago/blob/24d18cfcee784fc24b8cd8b3d22a1d21500d0275/src/Westsworld/TimeAgo.php#L56), line 56

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/0c6ef539-78b6-4856-8ea1-47ffe825759b/analyses/1)_

**Comment by andersahn** [comment]
https://github.com/jimmiw/php-time-ago/pull/50
