### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by playinteractive** [jimmiw/php-time-ago#56]
Hi Jimmi great class, good job! I've created the catalan translation. I attach the file in case you want to add it. Thanks.
[ca.txt](https://github.com/jimmiw/php-time-ago/files/1432743/ca.txt)

**Comment by esrefesen** [comment]
Hi,
You can read #32

**Comment by jimmiw** [comment]
Hello, just create a pull request and I'll add it.

**Comment by playinteractive** [comment]
Great, thanks!
