### ISSUE TITLE
Translations are problematic

### ISSUE THREAD

**Issue by cmfcmf** [jimmiw/php-time-ago#7]
It would be better to include `ago` in all the translation messages (i.e. `about 1 hour ago`), because:
- is there any use case where it isn't followed by `ago`?
- the German translation doesn't really work. `about 1 hour` would be translated by `etwa eine Stunde`, whereas `about 1 hour ago` would be translated by `vor etwa eineR Stunde` (please notice the `r`). So I can't just prepend `vor` (`ago`) to the translations of this library.

Do you see what I mean?

**Comment by jimmiw** [comment]
Hi,

I've added "ago" to the newest version, to make it easier to translate.

**Comment by cmfcmf** [comment]
Thanks!
