### ISSUE TITLE
Bug within isLessThan44Min29Secs 

### ISSUE THREAD

**Issue by nenad007** [jimmiw/php-time-ago#72]
Please fix this inside isLessThan44Min29Secs:

return $timeDifference->i < 45 &&
            $timeDifference->s < 30 &&
...

as soon the $timeDifference->s >= 30 it gives a wrong result back.

["years"]=> int(0) ["months"]=> int(0) ["days"]=> int(0) ["hours"]=> int(0) ["minutes"]=> int(36) ["seconds"]=> int(58) 
about 1 hour ago -> wrong 
 
3 seconds later: 

["years"]=> int(0) ["months"]=> int(0) ["days"]=> int(0) ["hours"]=> int(0) ["minutes"]=> int(37) ["seconds"]=> int(1) 
37 minutes ago -> correct

**Comment by jimmiw** [comment]
this is now ready in master and 3.0.4
