### ISSUE TITLE
Throws error: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Westsworld\\TimeAgo\\Translations\\En' not found in 

### ISSUE THREAD

**Issue by jonyking** [jimmiw/php-time-ago#77]
I used
 `
require_once ('include/Westsworld/TimeAgo.php');
$timeZone = null;
                                $timeAgo = new Westsworld\TimeAgo( $timeZone, 'De');
`

But throws the error:
`Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Westsworld\\TimeAgo\\Translations\\En' not found in `

**Comment by dhutapratama** [comment]
I think this issue must to be closed and start with create wiki page, guide for installation...???

**Comment by peter279k** [comment]
@dhutapratama, the `installing` section is available in `README`.

I think this issue should be closed now.
