### ISSUE TITLE
PHP Parse error?

### ISSUE THREAD

**Issue by Taapo** [jimmiw/php-time-ago#84]
I get:
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{'
in vendor/jimmiw/php-time-ago/src/Westsworld/TimeAgo.php on line 56?

**Comment by jimmiw** [comment]
What version of php are you using?

**Comment by jimmiw** [comment]
If you are below php7.0, you should properly stick to 3.0.x versions instead.

**Comment by Taapo** [comment]
ah, ok - on this machine I'm on 5.6

**Comment by Taapo** [comment]
Ok, I had to downgrade to 2.x versions before it started working - is that correct?

**Comment by jimmiw** [comment]
Seems correct. My bad on the versioning :)
5.6 was officially EOL at 1 jan 2019, so we stopped supporting it there abouts as well.
We are still supporting 7.0 though, eventhough it's EOL, but it might change soon.

Source: https://www.php.net/supported-versions.php

**Comment by dhutapratama** [comment]
Seems this issue was solved

**Comment by jimmiw** [comment]
you are correct @dhutapratama - thanks :)
