### ISSUE TITLE
Add "short" english language-class

### ISSUE THREAD

**Issue by MoPaMo** [jimmiw/php-time-ago#91]
I've just discovered *php-time-ago* and think its just great! There's just one thing:
In my opinion, 'about 1 hour ago' is a bit to long in some cases, so it would be great if you could add something like a shorter English language-class like this:

`  0 <-> 29 secs                                                             # => <1m

  30 secs <-> 1 min, 29 secs                                                # => 1m

  1 min, 30 secs <-> 44 mins, 29 secs                                       # => [2..44] m

  44 mins, 30 secs <-> 89 mins, 29 secs                                     # => ~1h

  89 mins, 29 secs <-> 23 hrs, 59 mins, 29 secs                             # => ~ [2..24] h

  23 hrs, 59 mins, 29 secs <-> 47 hrs, 59 mins, 29 secs                     # => 1d

  47 hrs, 59 mins, 29 secs <-> 29 days, 23 hrs, 59 mins, 29 secs            # => [2..29] d

  29 days, 23 hrs, 59 mins, 30 secs <-> 59 days, 23 hrs, 59 mins, 29 secs   # => ~1M

  59 days, 23 hrs, 59 mins, 30 secs <-> 1 yr minus 1 sec                    # => [2..12] M

  1 yr <-> 2 yrs minus 1 secs                                               # => 1y

  2 yrs <-> max time or date                                                # => >[2..X] y`

**Comment by jimmiw** [comment]
Hello @mopamo just make a new class that handles these translations and do a PR. Then i'll add it :)

**Comment by jimmiw** [comment]
merged PR :)
